# Generated by Django 5.2.11 on 2026-02-12 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('meal', 'Meal'), ('drink', 'Drink'), ('snacks', 'Snacks & Fun'), ('grocery', 'Grocery'), ('health', 'Health & Medication'), ('utility', 'Utility'), ('wear', 'Wear')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('meal', 'Meal'), ('drink', 'Drink'), ('snacks', 'Snacks & Fun'), ('grocery', 'Grocery'), ('health', 'Health & Medication'), ('utility', 'Utility'), ('wear', 'Wear')], max_length=50)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
