# Generated by Django 5.2.11 on 2026-02-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_income_delete_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('meal', 'Meal'), ('drink', 'Drink'), ('snacks', 'Snacks & Fun'), ('grocery', 'Grocery'), ('health', 'Health & Medication'), ('utility', 'Utility'), ('cosmetic', 'Cosmetic'), ('wear', 'Wear')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('meal', 'Meal'), ('drink', 'Drink'), ('snacks', 'Snacks & Fun'), ('grocery', 'Grocery'), ('health', 'Health & Medication'), ('utility', 'Utility'), ('cosmetic', 'Cosmetic'), ('wear', 'Wear')], max_length=50),
        ),
    ]
