# Generated by Django 5.2.11 on 2026-02-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_category_name_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('meal', 'Meal'), ('drink', 'Drink'), ('snacks', 'Snacks & Fun'), ('grocery', 'Grocery'), ('health', 'Health & Medication'), ('utility', 'Utility'), ('cosmetic', 'Cosmetic'), ('wear', 'Wear')], default='meal', max_length=50),
        ),
    ]
